name: ci
on: [push]

permissions:
  contents: read

jobs:
  build-and-test:
    name: >-
      CI
      ${{ matrix.os }}
      ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc]
        os: [macos-latest]
    
    env:
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Generate build config
        run: >-
          cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}"
      - name: Build
        run: >-
          cmake --build "${{ env.CMAKE_BUILD_DIR }}"
      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ./redis_simple_tests
      - name: Run Benchmarks
        working-directory: ${{ github.workspace }}/build
        run: ./memory_benchmark
